### ISSUE TITLE
Create a new NugetPackage for MvvmCross v4

### ISSUE THREAD

**Issue by benschi11** [autofac/Autofac.Extras.MvvmCross#1]
I think the code can be the same, but you need a new NugetPackage because the old one requires < 4.0.0 for MvvmCross and won't work.

**Comment by NPadrutt** [comment]
that would be very helpful. I copy pasted the existing code into my project since I couldn't build with the current package and v4

**Comment by gentledepp** [comment]
Hi! Already migrated and made PR, but AppVeyor build does not work.
Will need to fix it that weekend.
https://github.com/autofac/Autofac.Extras.MvvmCross/pull/3#issuecomment-187760876

**Comment by tillig** [comment]
Now that .NET Core RTM is out and the tooling is more stable, I'll be working on grabbing the contents of the PR(s) and getting MvvmCross 4 support out at the same time as .NET Core and Autofac 4 support. Thanks for your patience.

**Comment by tillig** [comment]
Pushed 4.0.0-rc3-227.
