### ISSUE TITLE
Update to accomodate breaking changes in MvvmCross 6

### ISSUE THREAD

**Issue by sfmskywalker** [autofac/Autofac.Extras.MvvmCross#11]
With the release of MvvmCross 6.0, the current version of Autofac.Extras.MvvmCross is broken unfortunately for that version. The updated `IMvxIoCProvider` now has support for child containers.

**Comment by RomaRudyak** [comment]
@sfmskywalker I have request in my project. thank you for your pull request with Autofac addaptor for mvvmcross.

Can I add changes to it for supporting MvvmCross 6.1.2?
I added implementation for IMvxIoCProvider interface for:
```csharp

		T IoCConstruct<T> () where T : class;

		T IoCConstruct<T> (IDictionary arguments) where T : class;

		T IoCConstruct<T> (object arguments) where T : class;

		T IoCConstruct<T> (params object[] arguments) where T : class;
// .... //
		object IoCConstruct (Type type, IDictionary arguments);

		object IoCConstruct (Type type, object arguments);

		object IoCConstruct (Type type, params object[] arguments);
```

**Comment by sfmskywalker** [comment]
Absolutely, by all means.
