### ISSUE TITLE
Autofac 5.2.0 compatibility

### ISSUE THREAD

**Issue by vazquezbonilla** [autofac/Autofac.Extras.MvvmCross#14]
Hi,

Is compatibility with latest stable Autofac 5.2.0 planned?

regards

**Comment by tillig** [comment]
Nope. As [noted in the README](https://github.com/autofac/Autofac.Extras.MvvmCross/blob/develop/README.md):

> **MAINTENANCE MODE**: This package is in maintenance-only mode. No new bug fixes or features will be added. If you would like to become an owner for this package and take responsibility for maintaining it, [visit us on the Google Groups and let us know](https://groups.google.com/forum/#!forum/autofac).
